# Generated by Django 5.1.2 on 2024-12-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Hakkımızda', 'verbose_name_plural': 'Hakkımızda'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='read_more_url',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='about_images/', verbose_name='Görsel 1'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='about_images/', verbose_name='Görsel 2'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Başlık'),
        ),
    ]
