# Generated by Django 5.1.2 on 2024-12-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aboutus_options_remove_aboutus_read_more_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='about_images/', verbose_name='Görsel ')),
                ('icon', models.ImageField(blank=True, upload_to='about_images/', verbose_name='İcon Görsel')),
            ],
            options={
                'verbose_name': 'Hizmetlerimiz',
                'verbose_name_plural': 'Hizmetlerimiz',
            },
        ),
    ]
