# Generated by Django 5.1.2 on 2024-12-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sosyal Medya Platformu')),
                ('icon_class', models.CharField(help_text="Örneğin: 'fab fa-facebook-f'", max_length=100, verbose_name='İkon Sınıfı (Font Awesome)')),
                ('url', models.URLField(verbose_name='Link')),
            ],
        ),
    ]
