# Generated by Django 5.1.2 on 2024-12-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosyal Medya', 'verbose_name_plural': 'Sosyal Medya'},
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon_image',
            field=models.ImageField(default='social_media_icons/default_image.jpg', upload_to='social_media_icons/', verbose_name='İkon Resmi'),
        ),
    ]
