# Generated by Django 5.1.2 on 2024-12-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Yeni Proje', help_text='Projenin adı.', max_length=200, verbose_name='Proje Adı')),
                ('project_description', models.TextField(blank=True, default='Açıklama yok', help_text='Proje hakkında açıklama.', null=True, verbose_name='Proje Açıklaması')),
                ('project_image', models.ImageField(blank=True, help_text='Proje ile ilgili resim', null=True, upload_to='projects/', verbose_name='Proje Resmi')),
                ('building_name', models.CharField(blank=True, default='Bina 1', help_text='Projede yer alan bina adı.', max_length=200, null=True, verbose_name='Bina Adı')),
                ('building_features', models.TextField(blank=True, default='Özellikler belirtilmemiş', help_text='Bina ile ilgili özellikler.', null=True, verbose_name='Bina Özellikleri')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
    ]
