# Generated by Django 5.1.2 on 2024-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='building_features',
        ),
        migrations.AddField(
            model_name='project',
            name='building_features1',
            field=models.TextField(blank=True, default='Özellikler belirtilmemiş', help_text='Bina ile ilgili özellikler.', max_length=100, null=True, verbose_name='Bina Özelliği 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='building_features2',
            field=models.TextField(blank=True, default='Özellikler belirtilmemiş', help_text='Bina ile ilgili özellikler.', max_length=100, null=True, verbose_name='Bina Özelliği 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='building_features3',
            field=models.TextField(blank=True, default='Özellikler belirtilmemiş', help_text='Bina ile ilgili özellikler.', max_length=100, null=True, verbose_name='Bina Özelliği 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='Proje Sloganınız'),
        ),
    ]
