# Generated by Django 5.1.2 on 2024-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_project_building_features1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Logo Adı')),
                ('image', models.ImageField(default='logo/default_image.jpg', upload_to='logo/', verbose_name='Logo Resmi')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logolar',
            },
        ),
    ]
